# ===========================
# Basic Site Settings
# ===========================
locale                   : "en-US"
site_theme               : "default"    # "default" or "air"
title                    : "AI4R³ Lab"
title_separator          : "-"
name                     : &name "Dr. Lenganji Simwanda"
description              : &description "AI for Risk, Reliability & Resilience — Academic portfolio of Dr. Lenganji Simwanda"
url                      : "https://lenganjisimwanda.github.io"  # Update if you deploy elsewhere
baseurl                  : "" 
repository               : "lenganjisimwanda/ai4r3lab"            # Your GitHub repo

# ===========================
# Site Author
# ===========================
author:
  avatar           : "profile.png" # Place your photo in /images
  name             : "Dr. Lenganji Simwanda"
  pronouns         : "he/him"
  bio              : "Founder & Lead Researcher at AI4R³ Lab | Postdoctoral Fellow, Czech Technical University in Prague"
  location         : "Prague, Czech Republic"
  employer         : "Czech Technical University in Prague"
  uri              : "https://lenganjisimwanda.com"
  email            : "lenganji.simwanda@cvut.cz"

  # Academic links
  googlescholar    : "https://scholar.google.com/citations?user=6ygH5-EAAAAJ&hl=en"
  orcid            : "https://orcid.org/0000-0002-1944-730X"
  researchgate     : "https://www.researchgate.net/profile/Lenganji-Simwanda"

  # Repositories and dev
  github           : "lenganjisimwanda"
  kaggle           : "lenganji"      # if you want to show Kaggle projects

  # Social media
  linkedin         : "https://www.linkedin.com/in/lenganji-simwanda/"
  twitter          : "SimwandaL"     # optional — your X handle if you use one

# ===========================
# Publication Categories
# ===========================
publication_category:
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'
  books:
    title: 'Books & Theses'

# ===========================
# Site Settings
# ===========================
teaser                   : "ai4r3lab-teaser.png" # Add a default social media image
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

comments:
  provider               : false

atom_feed:
  hide                   : false

# ===========================
# SEO
# ===========================
google_site_verification :
bing_site_verification   :

# ===========================
# Social Sharing
# ===========================
social:
  type                   : Organization
  name                   : "AI4R³ Lab"
  links:
    - https://scholar.google.com/citations?user=6ygH5-EAAAAJ
    - https://orcid.org/0000-0002-1944-730X
    - https://www.linkedin.com/in/lenganji-simwanda/

# ===========================
# Analytics
# ===========================
analytics:
  provider               : false

# ===========================
# Content Collections
# ===========================
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# ===========================
# Defaults
# ===========================
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true

# ===========================
# Markdown & Plugins
# ===========================
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

permalink: /:categories/:title/
timezone: Europe/Prague
